// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion():Promise<string>;

export function GetMicrophonePermissionStatus():Promise<number>;

export function GetServerURL():Promise<string>;

export function RequestMicrophonePermission():Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveServerURL(arg1:string):Promise<void>;
