// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion():Promise<string>;

export function GetServerURL():Promise<string>;

export function SaveServerURL(arg1:string):Promise<void>;
