// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function SaveServerURL(arg1) {
  return window['go']['main']['App']['SaveServerURL'](arg1);
}
