// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion():Promise<string>;

export function GetAPIURL():Promise<string>;

export function GetWSURL():Promise<string>;
