// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion():Promise<string>;

export function GetMicrophonePermissionStatus():Promise<number>;

export function GetServerURL():Promise<string>;

export function JoinVoiceChannel(arg1:string):Promise<void>;

export function LeaveVoiceChannel():Promise<void>;

export function RequestMicrophonePermission():Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveServerURL(arg1:string):Promise<void>;

export function SendVoiceAudio(arg1:Array<number>):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartVoiceChat(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function StopVoiceChat():Promise<void>;
