// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function GetMicrophonePermissionStatus() {
  return window['go']['main']['App']['GetMicrophonePermissionStatus']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function JoinVoiceChannel(arg1) {
  return window['go']['main']['App']['JoinVoiceChannel'](arg1);
}

export function LeaveVoiceChannel() {
  return window['go']['main']['App']['LeaveVoiceChannel']();
}

export function RequestMicrophonePermission() {
  return window['go']['main']['App']['RequestMicrophonePermission']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveServerURL(arg1) {
  return window['go']['main']['App']['SaveServerURL'](arg1);
}

export function SendVoiceAudio(arg1) {
  return window['go']['main']['App']['SendVoiceAudio'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartVoiceChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartVoiceChat'](arg1, arg2, arg3, arg4);
}

export function StopVoiceChat() {
  return window['go']['main']['App']['StopVoiceChat']();
}
